package com.example.ui.screens

import androidx.compose.animation.*
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.ui.components.AppTopBar
import com.example.ui.theme.*
import com.example.ui.viewmodel.BookReaderViewModel

@Composable
fun ExportBookScreen(
    viewModel: BookReaderViewModel,
    modifier: Modifier = Modifier
) {
    val book by viewModel.bookOptionsTarget.collectAsState()
    var isGenerating by remember { mutableStateOf(false) }
    var isGenerated by remember { mutableStateOf(false) }

    val currentBook = book ?: return

    Scaffold(
        topBar = {
            AppTopBar(
                title = "خروجی فایل کتاب",
                subtitle = currentBook.title,
                onBack = { viewModel.goBack() }
            )
        },
        bottomBar = {
            Surface(
                color = Background,
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(16.dp)
            ) {
                if (!isGenerated) {
                    Button(
                        onClick = {
                            isGenerating = true
                            isGenerated = true
                            isGenerating = false
                            viewModel.showSnackbar("فایل .bookapp با موفقیت ساخته شد")
                        },
                        shape = RoundedCornerShape(14.dp),
                        colors = ButtonDefaults.buttonColors(containerColor = Primary),
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(52.dp)
                            .testTag("generate_bookapp_button")
                    ) {
                        Icon(Icons.Filled.FileDownload, contentDescription = null)
                        Spacer(modifier = Modifier.width(8.dp))
                        Text("تولید فایل کتاب (.bookapp)", fontWeight = FontWeight.Bold, fontSize = 14.sp, color = Color.White)
                    }
                } else {
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(10.dp)
                    ) {
                        OutlinedButton(
                            onClick = { viewModel.showSnackbar("فایل در پوشه Downloads ذخیره شد") },
                            shape = RoundedCornerShape(12.dp),
                            modifier = Modifier
                                .weight(1f)
                                .height(50.dp)
                        ) {
                            Icon(Icons.Outlined.SaveAlt, contentDescription = null, tint = Primary)
                            Spacer(modifier = Modifier.width(6.dp))
                            Text("ذخیره در حافظه", fontSize = 13.sp, fontWeight = FontWeight.Bold)
                        }

                        Button(
                            onClick = { viewModel.showSnackbar("منوی اشتراک‌گذاری باز شد") },
                            shape = RoundedCornerShape(12.dp),
                            colors = ButtonDefaults.buttonColors(containerColor = Primary),
                            modifier = Modifier
                                .weight(1f)
                                .height(50.dp)
                        ) {
                            Icon(Icons.Outlined.Share, contentDescription = null)
                            Spacer(modifier = Modifier.width(6.dp))
                            Text("اشتراک‌گذاری", fontSize = 13.sp, fontWeight = FontWeight.Bold, color = Color.White)
                        }
                    }
                }
            }
        },
        containerColor = Background,
        modifier = modifier.testTag("export_book_screen")
    ) { innerPadding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(innerPadding)
                .padding(horizontal = 16.dp)
                .verticalScroll(rememberScrollState())
        ) {
            Spacer(modifier = Modifier.height(10.dp))

            // Package contents card
            Surface(
                shape = RoundedCornerShape(18.dp),
                color = Surface,
                border = BorderStroke(1.dp, Border),
                modifier = Modifier.fillMaxWidth()
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Text(
                        text = "محتوای بسته کتاب (.bookapp)",
                        fontWeight = FontWeight.Bold,
                        fontSize = 15.sp,
                        color = TextPrimary,
                        modifier = Modifier.padding(bottom = 12.dp)
                    )

                    ExportContentItem(text = "جلد، متادیتا و اطلاعات شناسنامه‌ای کتاب")
                    ExportContentItem(text = "متن کامل تبدیل‌شده و بهینه‌سازی‌شده برای مطالعه روان")
                    ExportContentItem(text = "فهرست مطالب، سطوح فصل‌ها و پاورقی‌های تعاملی")
                    ExportContentItem(text = "تصاویر بهینه‌شده به همراه توضیحات")

                    Spacer(modifier = Modifier.height(8.dp))

                    Surface(
                        shape = RoundedCornerShape(10.dp),
                        color = SecondarySurface,
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Row(
                            modifier = Modifier.padding(10.dp),
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(8.dp)
                        ) {
                            Icon(
                                imageVector = Icons.Outlined.Lock,
                                contentDescription = null,
                                tint = Primary,
                                modifier = Modifier.size(18.dp)
                            )
                            Text(
                                text = "نشانک‌ها و جایگاه مطالعه شخصی شما در این فایل قرار نمی‌گیرد.",
                                fontSize = 11.sp,
                                color = TextSecondary
                            )
                        }
                    }
                }
            }

            Spacer(modifier = Modifier.height(16.dp))

            // Success Card when generated
            if (isGenerated) {
                Surface(
                    shape = RoundedCornerShape(18.dp),
                    color = SuccessBackground,
                    border = BorderStroke(1.dp, Primary.copy(alpha = 0.3f)),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Row(
                        modifier = Modifier.padding(16.dp),
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(14.dp)
                    ) {
                        Box(
                            modifier = Modifier
                                .size(44.dp)
                                .background(Primary, CircleShape),
                            contentAlignment = Alignment.Center
                        ) {
                            Icon(
                                imageVector = Icons.Filled.Check,
                                contentDescription = null,
                                tint = Color.White,
                                modifier = Modifier.size(24.dp)
                            )
                        }

                        Column(modifier = Modifier.weight(1f)) {
                            Text(
                                text = "${currentBook.title}.bookapp",
                                fontWeight = FontWeight.Bold,
                                fontSize = 14.sp,
                                color = Primary
                            )
                            Text(
                                text = "حجم فایل: ۱.۸ مگابایت · آماده انتقال و ارسال",
                                fontSize = 12.sp,
                                color = TextSecondary
                            )
                        }
                    }
                }

                Spacer(modifier = Modifier.height(16.dp))
            }

            // Health Checklist
            Text(
                text = "بررسی سلامت ساختار کتاب",
                fontWeight = FontWeight.Bold,
                fontSize = 14.sp,
                color = TextPrimary,
                modifier = Modifier.padding(bottom = 8.dp)
            )

            Surface(
                shape = RoundedCornerShape(16.dp),
                color = Surface,
                border = BorderStroke(1.dp, Border),
                modifier = Modifier.fillMaxWidth()
            ) {
                Column(modifier = Modifier.padding(14.dp)) {
                    ChecklistItem(title = "تمام ${currentBook.chaptersCount} فصل با موفقیت بسته‌بندی شدند")
                    ChecklistItem(title = "پاورقی‌ها و شماره‌گذاری بدون اشکال است")
                    ChecklistItem(title = "تصاویر فشرده‌سازی و بدون افت کیفیت ذخیره شدند")
                    ChecklistItem(title = "فایل با تمام نسخه‌های کتاب‌خوان سازگار است")
                }
            }

            Spacer(modifier = Modifier.height(24.dp))
        }
    }
}

@Composable
private fun ExportContentItem(text: String) {
    Row(
        modifier = Modifier.padding(vertical = 4.dp),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.spacedBy(8.dp)
    ) {
        Box(
            modifier = Modifier
                .size(6.dp)
                .background(Primary, CircleShape)
        )
        Text(
            text = text,
            fontSize = 12.sp,
            color = TextPrimary
        )
    }
}

@Composable
private fun ChecklistItem(title: String) {
    Row(
        modifier = Modifier.padding(vertical = 6.dp),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.spacedBy(10.dp)
    ) {
        Icon(
            imageVector = Icons.Filled.CheckCircle,
            contentDescription = null,
            tint = StatusSuccess,
            modifier = Modifier.size(18.dp)
        )
        Text(
            text = title,
            fontSize = 12.sp,
            color = TextPrimary
        )
    }
}
