package com.ketabkhan.reader.ui.screens

import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.ketabkhan.reader.ui.components.AppTopBar
import com.ketabkhan.reader.ui.theme.*
import com.ketabkhan.reader.ui.viewmodel.BookReaderViewModel
import com.ketabkhan.reader.util.AppConstants

@Composable
fun ExportBookScreen(
    viewModel: BookReaderViewModel,
    modifier: Modifier = Modifier
) {
    val book by viewModel.bookOptionsTarget.collectAsState()
    var isGenerated by remember { mutableStateOf(false) }

    val currentBook = book ?: return

    Scaffold(
        topBar = {
            AppTopBar(
                title = "خروجی فایل کتاب",
                subtitle = currentBook.title,
                onBack = { viewModel.goBack() }
            )
        },
        bottomBar = {
            Surface(
                color = Background,
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(16.dp)
            ) {
                Button(
                    onClick = {
                        viewModel.showSnackbar(AppConstants.MSG_EXPORT_BOOKAPP_DEV)
                    },
                    shape = RoundedCornerShape(14.dp),
                    colors = ButtonDefaults.buttonColors(containerColor = Primary),
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(52.dp)
                        .testTag("generate_bookapp_button")
                ) {
                    Icon(Icons.Filled.FileDownload, contentDescription = null)
                    Spacer(modifier = Modifier.width(8.dp))
                    Text("تولید فایل کتاب (.bookapp)", fontWeight = FontWeight.Bold, fontSize = 14.sp, color = Color.White)
                }
            }
        },
        containerColor = Background,
        modifier = modifier.testTag("export_book_screen")
    ) { innerPadding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(innerPadding)
                .padding(horizontal = 16.dp)
                .verticalScroll(rememberScrollState())
        ) {
            Spacer(modifier = Modifier.height(10.dp))

            // Package contents card
            Surface(
                shape = RoundedCornerShape(18.dp),
                color = Surface,
                border = BorderStroke(1.dp, Border),
                modifier = Modifier.fillMaxWidth()
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Text(
                        text = "محتوای بسته کتاب (.bookapp)",
                        fontWeight = FontWeight.Bold,
                        fontSize = 15.sp,
                        color = TextPrimary,
                        modifier = Modifier.padding(bottom = 12.dp)
                    )

                    ExportContentItem(text = "جلد، متادیتا و اطلاعات شناسنامه‌ای کتاب")
                    ExportContentItem(text = "متن کامل تبدیل‌شده و بهینه‌سازی‌شده برای مطالعه روان")
                    ExportContentItem(text = "فهرست مطالب، سطوح فصل‌ها و پاورقی‌های تعاملی")
                    ExportContentItem(text = "تصاویر بهینه‌شده به همراه توضیحات")

                    Spacer(modifier = Modifier.height(8.dp))

                    Surface(
                        shape = RoundedCornerShape(10.dp),
                        color = SecondarySurface,
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Row(
                            modifier = Modifier.padding(10.dp),
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(8.dp)
                        ) {
                            Icon(
                                imageVector = Icons.Outlined.Lock,
                                contentDescription = null,
                                tint = Primary,
                                modifier = Modifier.size(18.dp)
                            )
                            Text(
                                text = "نشانک‌ها و جایگاه مطالعه شخصی شما در این فایل قرار نمی‌گیرد.",
                                fontSize = 11.sp,
                                color = TextSecondary
                            )
                        }
                    }
                }
            }

            Spacer(modifier = Modifier.height(16.dp))

            // Health Checklist
            Text(
                text = "مشخصات بسته استاندارد کتاب",
                fontWeight = FontWeight.Bold,
                fontSize = 14.sp,
                color = TextPrimary,
                modifier = Modifier.padding(bottom = 8.dp)
            )

            Surface(
                shape = RoundedCornerShape(16.dp),
                color = Surface,
                border = BorderStroke(1.dp, Border),
                modifier = Modifier.fillMaxWidth()
            ) {
                Column(modifier = Modifier.padding(14.dp)) {
                    ChecklistItem(title = "شامل ${currentBook.chaptersCount} فصل به صورت متنی و ساختاریافته")
                    ChecklistItem(title = "پیوندهای پاورقی و شماره‌گذاری یکپارچه")
                    ChecklistItem(title = "ذخیره‌سازی بهینه بدون افت کیفیت")
                    ChecklistItem(title = "سازگار با تمامی نسخه‌های کتاب‌خوان")
                }
            }

            Spacer(modifier = Modifier.height(24.dp))
        }
    }
}

@Composable
private fun ExportContentItem(text: String) {
    Row(
        modifier = Modifier.padding(vertical = 4.dp),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.spacedBy(8.dp)
    ) {
        Box(
            modifier = Modifier
                .size(6.dp)
                .background(Primary, CircleShape)
        )
        Text(
            text = text,
            fontSize = 12.sp,
            color = TextPrimary
        )
    }
}

@Composable
private fun ChecklistItem(title: String) {
    Row(
        modifier = Modifier.padding(vertical = 6.dp),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.spacedBy(10.dp)
    ) {
        Icon(
            imageVector = Icons.Filled.CheckCircle,
            contentDescription = null,
            tint = StatusSuccess,
            modifier = Modifier.size(18.dp)
        )
        Text(
            text = title,
            fontSize = 12.sp,
            color = TextPrimary
        )
    }
}
